export const LOAD_SHOP = 'LOAD_SHOP';
export const ADD_ITEM_TO_BAG = 'ADD_ITEM_TO_BAG';
export const SELECTED_ITEM = 'SELECTED_ITEM';
export const ADD_TOTAL_PRICE = 'ADD_TOTAL_PRICE';
export const ADD_ITEM_TO_FAVORITE = 'ADD_ITEM_TO_FAVORITE';
export const DELETE_ITEM_TO_FAVORITE = 'ADD_ITEM_TO_FAVORITE';





